name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libtool autoconf

    - name: Build and install CppUnit
      run: |
        wget https://dev-www.libreoffice.org/src/cppunit-1.14.0.tar.gz
        tar xf cppunit-1.14.0.tar.gz
        cd cppunit-1.14.0
        ./configure
        make
        sudo make install

    - name: Build and Test
      run: |
        make
        make test

